---
title: "clustered_heatmap"
output: html_document
author: Krifa Sallouha
date: "2024-04-22"
---


```{r setup, include=FALSE}
library(cluster)
library(readxl)
library(pheatmap)
```

```{r setup, include=FALSE}
# Define the working directory and file path
WORKING_DIR <- "  "
file_path <- file.path(WORKING_DIR, " .xlsx")


p_value_data <- read_excel(file_path)
p_value_data <- as.data.frame(p_value_data)

# Set gene labels as row names
p_value_data$unique_id <- make.unique(as.character(p_value_data$fly_gene))

row.names(p_value_data) <- p_value_data$unique_id

# Prepare phenotype data by selecting 
phenotype_data <- p_value_data[, c("fold_change_EDD", "fold_change_ESD", "fold_change_FS", 
                                   "fold_change_HP_median", "fold_change_DI_median", "fold_change_SI_median",   
                                   "fold_change_AI","fold_change_CO","fold_change_MAD_SI","fold_change_MAD_DI","fold_change_MAD_HP")]

# Prepare significance index data 
significance_index_data <- p_value_data[, c("Significance_Index_EDD", "Significance_Index_ESD", "Significance_Index_FS", 
                                            "Significance_Index_HP_median", "Significance_Index_DI_median", "Significance_Index_SI_median",                        
                                            "Significance_Index_AI","Significance_Index_CO","Significance_Index_MAD_SI","Significance_Index_MAD_DI","Significance_Index_MAD_HP")]


# Replace 'NS' with an empty string in the significance_index_data
significance_index_data[] <- lapply(significance_index_data, function(x) {
    x <- as.character(x)
    x[x == "NS"] <- ""  # Replace 'NS' with an empty string
    x  # Return the modified data
})

#convert the phenotye_data to numeric
phenotype_data[] <- lapply(phenotype_data, function(x) as.numeric(as.character(x)))

# Update column names to be more readable
colnames(phenotype_data) <- c("EDD", "ESD", "FS", "HP_median", "DI_median", "SI_median", "AI", "CO","MAD_SI", "MAD_DI", "MAD_HP")




# Define parameters and their groupings
parameters <- c("EDD", "ESD", "FS", "HP_median", "DI_median", "SI_median", "AI", "CO","MAD_SI", "MAD_DI", "MAD_HP")
cardiac_phenotypes_type <- c("Structure", "Structure", "Structure", "Rhythm", "Rhythm", "Rhythm", "Rhythm", "Rhythm/Structure","Rhythm","Rhythm","Rhythm")
param_annotation <- data.frame(cardiac_phenotypes_type = factor(cardiac_phenotypes_type, levels = c("Structure", "Rhythm","Rhythm/Structure" )))
rownames(param_annotation) <- parameters

# Determine maximum value for scaling
max_val <- max(phenotype_data, na.rm = TRUE)

# Create breaks and corresponding colors
breaks <- c(seq(0.3, 0.9999999999999, length.out = 101), seq(1, max_val, length.out = 100))
colors <- c(colorRampPalette(c("blue", "white"))(101), colorRampPalette(c("white", "red"))(100))
annotation_colors <- list(cardiac_phenotypes_type = c("Structure" = "lightgreen", "Rhythm" = "plum1", "Rhythm/Structure" = "yellow2"))

# Create the heatmap with annotations and custom breaks/colors
p <- pheatmap(
  as.matrix(phenotype_data),
  display_numbers = as.matrix(significance_index_data), 
  clustering_distance_rows = "euclidean",
  clustering_distance_cols = "euclidean",
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  annotation_col  = param_annotation,
  annotation_colors = annotation_colors,
  treeheight_col = 60,
  treeheight_row =  250,
  show_rownames = TRUE,
  show_colnames = TRUE,
  fontsize_row = 13,
  fontsize_col = 15,
  cellheight = 30,
  cellwidth = 30,
  margins = c(5, 15),
  fontsize_number = 10,
  breaks = breaks,
  color = colors,
  number_color = "black",
  main = "Gene KD Expression Effect Patterns Across Cardiac Parameters - 1wf"
)

# Save the heatmap
ggsave("clustered_heatmap.png", plot = p$gtable, width = 11, height = 10, dpi = 300)



```
