---
title: "Normalization to Control Group"
author: Krifa Sallouha
output:
  html_document:
    toc: yes
    toc_float: yes
  word_document:
    toc: yes
params:
  analysis: One time point
  control: "60100"
  experiments: "101505,101695,101767,101903,102995,103570,104102,104485,104775,105315,105499,105500,105749,106198,106350,106833,106919,106961,107027,107071,107349,108070,108134,108395,108623,110164,110647" 
---

# Initiation

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)        
library(data.table)    
library(stringr)      
library(lubridate) 
library(openxlsx)      
library(svDialogs)   
```


```{r data setup, include=TRUE}

# Prompt user to select folder containing raw .csv files
rawdata_folder <- selectDirectory(caption = "Select Folder with rawdata files", label = "rawdata files")
setwd(rawdata_folder)

# List all .csv files
filelist <- NULL
filelist$csv <- list.files(".", pattern = "\\.csv$", recursive = TRUE)
total <- length(filelist$csv)
if(total == 0) stop("THERE IS NO CSV FILES IN THE CURRENT LOCATION.")

# Read all CSV files and merge into one data table
datalist <- list()
for(f in 1:total){
  dataframe <- read.csv(filelist$csv[f])
  datalist[[f]] <- dataframe
}
all_data <- rbindlist(datalist)

# Extract replicate date from filename (format: yymmdd)
cxd_files <- unlist(all_data$cxd_file)
all_data <- all_data[, cxd_date := as.Date(mdy(str_extract(cxd_files, "[:digit:]{6}")))]

# Define parameter list to normalize
parameters <- c("EDD", "ESD", "FS", "HP_median", "DI_median", "relaxtime", "SI_median", 
                "AI", "SV", "CO", "peaked_median", "min.velocity", "max.velocity", 
                "MAD_SI", "MAD_DI", "MAD_HP", "tt10r_median", "MAD_tt10r")

condition_list <- unique(all_data$CODE)
control_code <- params$control
experiment_codes <- unlist(strsplit(params$experiments, ","))

# Subset data: control group and experiment groups
control <- all_data %>%
  filter(CODE == control_code)

experiments <- all_data %>%
  filter(CODE %in% experiment_codes)

```
# Normalize each parameter in both control and experimental data using control mean

```{r , include=TRUE}

# Compute mean of each parameter in the control group
control_mean <- apply(select(control, all_of(parameters)), 2, mean, na.rm = TRUE)

for (param in parameters) {
  if (param %in% colnames(control)) {
    # Scale experimental values
    experiments[[param]] <- experiments[[param]] / control_mean[param]
    
    # Scale control values
    control[[param]] <- control[[param]] / control_mean[param]
  }
}


normalized_data <- rbind(control, experiments)

# Export scaled data to CSV and Excel
write.csv(normalized_data, file = "normalized_data.csv", row.names = FALSE)
write.xlsx(normalized_data, file = "normalized_data.xlsx", row.names = FALSE)

```

